### PR TITLE
Scenario G: custom PHP SAPI

### PR DESCRIPTION
**Pull request by mnapoli**
Scenario G is about writing a custom PHP SAPI to fit our needs.

*What is a SAPI?* A SAPI is a "mode" to run PHP. For example PHP-CLI is the SAPI to run PHP scripts in the terminal (i.e. the `php` binary). PHP-FPM is a SAPI to run PHP with a webserver like Apache or Nginx. The `php -S` built-in webserver is a special mode of PHP-CLI.

This new SAPI is actually inside the PHP-CLI SAPI, just like `php -S` is.

It can be used by running a script with the `-L` option (for *loop*):

```bash
php -L script.php
```

That will execute `script.php` in a loop.

The big difference with simply executing `script.php` in a loop using any other mean is that **`script.php` will run in the same process every time, but the memory will be reset every time.**

### Why?

It allows to **remove the overhead of starting a new process for every request**.

This is basically just like PHP-FPM/FastCGI: one PHP process handles many requests except from the perspective of a PHP developer all the variables/memory/global state is reset on every request.

This is basically like scenario A (React/Amp/Aerys/Swoole/etc.) except we keep the request isolation that PHP has always had.

Why is it interesting with AWS Lambda mainly? Because AWS Lambda doesn't support FastCGI, so everything we've created around it (PHP-FPM) doesn't work there.

### Results

For both PHP and Symfony I get very very good processing times: 10ms average and 6ms minimum!

These numbers are almost as good as solution A without the problem of solution A (no request isolation).

### How?

I worked on this new `php -L` mode here: https://github.com/mnapoli/php-src/pull/2

Note that this is experimental, I am not a C developer :( To merge this into PHP this needs to go through a RFC, get accepted, get reviewed, tested and released in a new PHP version. But if we have a solid use case this will definitely help get the ball moving.

I'd really appreciate any kind of advice, idea to make it even faster, code review, help, etc.

Also the good thing about this new mode is that it is not specific to AWS Lambda: it can be useful to write PHP workers (the advantage would be to keep isolation between jobs while keeping it simple and fast to run). Maybe there are other use cases that could pop up too.

### Examples

Example of `bootstrap`:

```sh
#!/bin/sh

echo "Cold start"

php -c/opt/php.ini -L index.php
```

Example of `index.php` (this script is looped):

```php
require __DIR__ . '/vendor/autoload.php';

$kernel = new Kernel('prod', false);
$symfonyAdapter = new SymfonyAdapter($kernel);

// This is a blocking HTTP call until an event is available
[$event, $invocationId] = waitForEventFromLambdaApi($lambdaRuntimeApi);

$request = RequestFactory::fromLambdaEvent($event);
$response = $symfonyAdapter->handle($request);
$lambdaResponse = LambdaResponse::fromPsr7Response($response);

signalSuccessToLambdaApi($lambdaRuntimeApi, $invocationId, $lambdaResponse);
```

### CODE REVIEW

**Comment by ragboyjr** [comment]
dude, you are a beast. I can't wait to see how this all plays out in the coming years. Definitely feel like this could be a big deal. Would be great to come up with a SF skeleton that's optimized for running in aws, logs go to cloudwatch, s3 file integration, etc etc.

**Comment by barryvdh** [comment]
Nice idea. You could probably implement this as an extension (no idea/experience myself), to circumvent the rfc/ release process.

I do wonder how this would compare to the preload functions in 7.4, which should more aggressively keep the classes in memory, compared to just opcache. 

In the other PR you mention this bypasses the time to start a new process, but I don't think that's actually taking much time with fastcgi, seeing as the plain PHP version for E and F is done within 2ms, including parsing the lamdba event, starting a new request and returning it.

Your php version isn't faster, bit the symfony one is. That is as fast as plain PHP? Which seems weird, as it's doing much more. Are you sure no memory is shared between requests? Eg. In the container etc.

**Comment by barryvdh** [comment]
Actually, the plain PHP is 5ms slower? Thats also odd, isnt it?

**Comment by mnapoli** [comment]
> You could probably implement this as an extension (no idea/experience myself), to circumvent the rfc/ release process.

Yep but I have no idea if it's possible to affect the PHP-CLI SAPI that much from an extension. If possible that would be indeed a much better option.

Regarding the comparison to FastCGI I agree that there shouldn't be too much difference. What we are saving is (I think) mainly the overhead of converting and passing of events and responses through the FastCGI protocol.

> Your php version isn't faster, bit the symfony one is. That is as fast as plain PHP? Which seems weird, as it's doing much more. Are you sure no memory is shared between requests? Eg. In the container etc.
>
> Actually, the plain PHP is 5ms slower? Thats also odd, isnt it?

Yes I was surprised by that too. I think there is the overhead of resetting the state every time which creates a baseline of response time.

If you are able to test also on your side that would be great to increase confidence in the results. Also you can check here that this is indeed the Symfony homepage ^^ https://g9fzxul00f.execute-api.us-east-2.amazonaws.com/Prod

And I re-ran the benchmark and found even better response times… I updated the README ;) And at some point I got worse response time for PHP… I guess Lambdas are not that stable when under 10ms execution time 🤔

**Comment by barryvdh** [comment]
Hmm I ran this, but it just times out. Are you sure this is the correct base image etc?

Using make:preview after pulling the latest master:

```
2018-12-10 22:02:39 Invoking bref.php (provided)
2018-12-10 22:02:39 arn:aws:lambda:us-east-2:416566615250:layer:php-72:5 is already cached. Skipping download
2018-12-10 22:02:39 Requested to skip pulling images ...

2018-12-10 22:02:39 Mounting /Users/barry/Sites/bref-bootstrap-benchmarks/g/php as /var/task:ro inside runtime container
Cold start
2018-12-10 22:02:50 Function 'DemoFunction' timed out after 10 seconds
2018-12-10 22:02:51 Function returned an invalid response (must include one of: body, headers or statusCode in the response object). Response received: 
2018-12-10 22:02:51 127.0.0.1 - - [10/Dec/2018 22:02:51] "GET / HTTP/1.1" 502 -
2018-12-10 22:02:51 Invoking bref.php (provided)
2018-12-10 22:02:51 arn:aws:lambda:us-east-2:416566615250:layer:php-72:5 is already cached. Skipping download
2018-12-10 22:02:51 Requested to skip pulling images ...

2018-12-10 22:02:51 Mounting /Users/barry/Sites/bref-bootstrap-benchmarks/g/php as /var/task:ro inside runtime container
Cold start
2018-12-10 22:03:02 Function 'DemoFunction' timed out after 10 seconds
2018-12-10 22:03:02 Function returned an invalid response (must include one of: body, headers or statusCode in the response object). Response received: 
```

**Comment by barryvdh** [comment]
Sorry my bad, was a composer issue. Seems to be working, will see if I can benchmark it.

**Comment by mnapoli** [comment]
@barryvdh I figured out why PHP was slower: it wasn't using the latest PHP runtime with opcache ;)

That's fixed in #16 (and PHP is now faster!)

**Pull request merged**
