### PR TITLE
Scenario H - Take Two

### PR DESCRIPTION
**Pull request by bubba-h57**
Cleaned up and resubmitted.

### CODE REVIEW

**Comment by barryvdh** [comment]
What is the performance for this?

**Comment by bubba-h57** [comment]
Symfony Stats

**Comment by barryvdh** [comment]
Cool, perhaps rerun it so the cold start is excluded. That's what I did with mine. And add it to the readme table :)

**Comment by mnapoli** [comment]
Thanks, I'm updating the README after merging.

**Pull request merged**
